baseURL = "https://xypnox.github.io/blag/"
title = "The Blag"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

publishDir = "docs"

disqusShortname = "xypnox-blag"
googleAnalytics = ""

Paginate = 8
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Emoji Support
enableEmoji = true

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "My Blag, a collection of Physics, Computing and Philosophy"
title404 = "This Dimension contains nothing!!!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "@xypnox"
startYear = "2017"
suffix = ""

[params.comments]
enable = true

[params.sidebar]
enable = false

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
accentColor = "#33df97"


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "xypnox @ gmail . com"
facebook = "xypnox"
github = "xypnox"
instagram = "xypnox"
twitter = "xypnox"
telegram = "xypnox"

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","telegram"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
weight = -100
url = "/"

[[menu.main]]
name = "Posts"
weight = -99
url = "/posts/"

[[menu.main]]
name = "Tags"
weight = -90
url = "/tags/"

[[menu.main]]
name = "Repo"
weight = 10
identifier = "repository"
url = "https://github.com/xypnox/blag"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
